version: '2.2'
services:
    php_xdebug:
        container_name: dm_php
        image: registry.gitlab.com/spyoutdoor-projects/registry:php-fpm-xdebug
        volumes:
            - .:/var/www/app
            - ./etc/php-xdebug/:/usr/local/etc/
            - /var/log/php-fpm:/var/log/php-fpm
            - /var/log/php:/var/log/php
        env_file:
            - .env
        networks:
            vpcbr:
                ipv4_address: 10.7.0.4

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                -   subnet: 10.7.0.0/16
                    gateway: 10.7.0.1